version: 0.0
os: linux
files:
  - source: /
    destination: /bin/smashbot
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      runas: root
  ApplicationStart:
    - location: scripts/start_bot
      runas: root
  ApplicationStop:
    - location: scripts/stop_bot
      runas: root