name: Deploy

on:
  push:
    branches: [master]
    paths-ignore: ['README.md', 'sql/*', 'scripts/*']

jobs:
  build_and_deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - name: Auth to GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.DEPLOYER_SVC_KEY }}'
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        version: '>= 363.0.0'
        project_id: discord-smashbot
    - name: Auth to gcr.io
      run: |
        gcloud auth configure-docker gcr.io
    - name: Build and deploy docker image to GCR
      run: |
        docker build -t gcr.io/discord-smashbot/smashbot:latest .
        docker push gcr.io/discord-smashbot/smashbot:latest
    - name: Restart VM to pick up latest docker image
      run: |
        gcloud compute instances stop smashbot-container-vm --zone=us-central1-a
        gcloud compute instances start smashbot-container-vm --zone=us-central1-a
