name: Deploy

on:
  push:
    branches: [master]

jobs:
  build_and_deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
    - name: Configure gcloud with deployer service account creds
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        project_id: discord-smashbot
        service_account_key: ${{ secrets.DEPLOYER_SVC_KEY }}
        export_default_credentials: true
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - name: Build and deploy docker image to GCR
      run: |
        gcloud auth configure-docker
        docker build -t gcr.io/discord-smashbot/smashbot:latest .
        docker push gcr.io/discord-smashbot/smashbot:latest
    - name: Restart VM with latest docker image
      run: |
        gcloud compute instances stop smashbot-container-vm --zone=us-central1-a
        gcloud compute instances start smashbot-container-vm --zone=us-central1-a